oracle:
  datasource:
    extensions:
      initSql: alter session set current_schema=kivi_core
    jdbcUrl: jdbc:oracle:thin:@clo-ora21xe
    username: kivi_core
    password: booble34
spring:
  freemarker:
    expose-request-attributes: true
