### Создание платежа. Перевод денег от Яковлеву Измайлову
POST http://localhost:8080/api/v1/payments/
Content-Type: application/json

{
  "fromClientId": "361",
  "toClientId": "363",
  "currencyId": 643,
  "summa": 666.66,
  "paymentDetail": {
    "note": "Измайлов, ты демон! Возвращаю проспоренное бабло"
  }
}


### Получение информации по платежу
GET http://localhost:8080/api/v1/payments/168



